kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: elasticsearch
  namespace: openshift-logging
spec:
  to:
    kind: Service
    name: elasticsearch
    weight: 100
  port:
    targetPort: elasticsearch
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None