---

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Generic Event Webhook 
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: TIMESTAMP -              🟢 START - AIOPS WEBHOOK
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"




- name: LOAD PARAMETERS -        👓 Load parameters
  include_vars: ../00_config_cp4waiops.yaml

- name: EVENTS-WEBHOOK -      🧻 Delete previous CP4WAIOPS Generic Event Webhook  
  kubernetes.core.k8s:
    state: absent
    template: ./templates/waiops-webhook/create-cp4waiops-event-gateway.j2

- name: EVENTS-WEBHOOK -      🚀 Create CP4WAIOPS Generic Event Webhook  
  kubernetes.core.k8s:
    state: present
    template: ./templates/waiops-webhook/create-cp4waiops-event-gateway.j2
