

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Open Doc
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: LOAD PARAMETERS -        👓 Load parameters
  include_vars: ../00_config_cp4waiops.yaml


- name: DOCUMENTATION -          📥 WRITE TO LOGFILE
  shell: |
    export MESSAGE=" 🌏 Open doc at https://github.ibm.com/NIKH/aiops-install-ansible-33#4-ai-manager-post-install-configuration"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes


- name: DOCUMENTATION -          🌏 Open Documentation
  shell: |
    export URL={{URL_STEP_2}}
    if [ -x "$(command -v open)" ]; then
      open $URL
    else 
      if [ -x "$(command -v firefox)" ]; then
        firefox $URL
      else 
        if [ -x "$(command -v google-chrome)" ]; then
          google-chrome $URL
        fi
      fi
    fi
  ignore_errors: yes



