

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for Common Services being ready
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


- name: LOGGING -                📥 WRITE TO LOGFILE
  shell: |
    export MESSAGE=" 🕦 Wait for Common Services to become ready"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes


# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for Common Services
# --------------------------------------------------------------------------------------------------------------------------------------

- name: CHECK -                  🕦 Wait for more than >{{ CS_NS_MIN_PODS }} pods in namespace ibm-common-services (this might take some time)
  shell: |
    NUM_PODS=$(oc get po -n ibm-common-services | wc -l)
    echo $NUM_PODS
  register: kubectl_num_pods
  until: kubectl_num_pods.stdout|int > CS_NS_MIN_PODS
  retries: 50
  delay: 15




- name: CHECK -                  🕦 Wait for ibm-common-services to become ready (this might take some time)
  shell: oc get po -n ibm-common-services | grep -v Running |grep -v Completed | grep -c ""
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout == "1"
  retries: 150
  delay: 15



- name: LOGGING -                📥 WRITE TO LOGFILE
  shell: |
    export MESSAGE=" ✅ Common Services is ready"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes
