#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
#  CP4WAIOPS v3.3 - Ansible Install Parameters
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS AI Manager INSTALL PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# CP4WAIOPS Namespace for installation
WAIOPS_NAMESPACE: cp4waiops

# CP4WAIOPS Size of the install (small: PoC/Demo, tall: Production)
WAIOPS_SIZE: small # Leave at small unless you know what you're doing

# Version of the catalog subscription
SUBSCRIPTION_CHANNEL: v3.3



# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Storage Class Override
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# Override the Storage Class auto detection (not_configured, ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
STORAGECLASS_FILE_OVERRIDE: not_configured
#STORAGECLASS_FILE_OVERRIDE: ibmc-file-gold-gid          # ROKS
#STORAGECLASS_FILE_OVERRIDE: rook-cephfs                 # FYRE
#STORAGECLASS_FILE_OVERRIDE: nfs-client                  # TEC
STORAGECLASS_BLOCK_OVERRIDE: not_configured
#STORAGECLASS_BLOCK_OVERRIDE: ibmc-block-gold            # ROKS
#STORAGECLASS_BLOCK_OVERRIDE: rook-cephfs                # FYRE
#STORAGECLASS_BLOCK_OVERRIDE: nfs-client                 # TEC




# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Event Manager INSTALL PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# CP4WAIOPS Namespace for installation
EVTMGR_NAMESPACE: cp4waiops-evtmgr

EVTMGR_CHANNEL: v1.7



# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# DEMO INSTALL PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# Print all credentials at the end of the installation
PRINT_LOGINS: true






# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# MODULE INSTALL PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# Install Rook-Ceph (Should Rook-Ceph be installed (automatic: install when on IBM Fyre) (enable, automatic, disable))
ROOK_CEPH_INSTALL_MODE: automatic


# LDAP Domain
LDAP_DOMAIN: ibm.com
# LDAP Base
LDAP_BASE: dc=ibm,dc=com
# LDAP Admin Password
LDAP_ADMIN_PASSWORD: P4ssw0rd!


# Turbonomic Storage Class (ibmc-block-gold, rook-cephfs, nfs-client, ...)
STORAGE_CLASS_TURBO: ibmc-block-gold

# Humio Storage Class (ibmc-block-gold, rook-cephfs, nfs-client, ...)
STORAGE_CLASS_HUMIO: ibmc-block-gold

# Storage Class for Infra Management (must be RWX)
INFRA_STORAGE_CLASS_FILE: ibmc-file-gold-gid

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# OCP LOGIN PARAMETERS (if you want to login automatically)
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
OCP_LOGIN: false
OCP_URL: not_configured
OCP_TOKEN: not_configured

#Version of your OCP Cluster (override by setting manually - 4.6, 4.7,...)
OCP_MAJOR_VERSION: automatic





# *************************************************************************************************************************************************
# *************************************************************************************************************************************************
# *************************************************************************************************************************************************
# DO NOT EDIT BELOW
# *************************************************************************************************************************************************
# *************************************************************************************************************************************************
# *************************************************************************************************************************************************





























































# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# WAIOPS INSTALL PARAMETERS (do not change)
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# Name of the CP4WAIOPS instance
#WAIOPS_NAME: ibm-aiops
WAIOPS_NAME: ibm-cp-watson-aiops
#WAIOPS_NAME: ibm-cp-watson-aiops
# Create externally accessible Route for Topology
CREATE_TOPO_ROUTE: true
# Create externally accessible Routes  (security risk!)
# Flink
# AI Manager API Route
# Datalayer API
CREATE_EXTERNAL_ROUTES: true

# Install the EvtManager --> AI Manager Gateway
INSTALL_GATEWAY: true
# Number of Pods to be expected in final CP4WAIOPS Namespace
WAIOPS_NS_MIN_PODS_FINAL: 110
# Number of Pods to be expected in final AI Manager Namespace
CS_NS_MIN_PODS: 35
# Number of Pods to be expected in final RookCeph Namespace
ROOK_NS_MIN_PODS: 34
# Number of Pods to be expected in final Event MAnager Namespace
EVTMGR_NS_MIN_PODS_FINAL: 70





# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# IBM ENTITLED REGISTRY PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
# IBM Entitled Registry
ENTITLED_REGISTRY: cp.icr.io
ENTITLED_REGISTRY_USER: cp
#ENTITLED_REGISTRY_KEY: TOKEN
CATALOG_IMAGE: icr.io/cpopen/ibm-operator-catalog:latest





# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# URLs for Documentation
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
URL_STEP_1: https://github.ibm.com/NIKH/aiops-install-ansible-fvt-33#3-ai-manager-configuration
URL_STEP_2: https://github.ibm.com/NIKH/aiops-install-ansible-fvt-33#4-ai-manager-post-install-configuration
URL_STEP_3: https://github.ibm.com/NIKH/aiops-install-ansible-fvt-33#5-ai-manager-finalize-configuration























































































































































































# ENTITLED_REGISTRY: cp.stg.icr.io
# ENTITLED_REGISTRY_USER: cp
# CATALOG_IMAGE: cp.stg.icr.io/cp/ibm-watson-aiops-catalog:v3.3.0-20220318.1607-5b33fc8b1


# ENTITLED_REGISTRY: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com
# ENTITLED_REGISTRY_USER: nikh@ch.ibm.com
# CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:ibm-watson-aiops-catalog:v3.3.1-20220401.0402-d8321a862

#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.3.0-20220302.0400-3b4003642
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v0.1.0-20220228.0226-9683f80a9
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.3.0-20220301.1845-1cebcbd5b
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.3.0-20220303.1400-02e39a2b9
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.3.0-20220303.1400-02e39a2b9
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.3.0-20220309.0801-8a3d96276
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.3.0-20220311.0001-1e48dd0ee
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.3.0-20220314.0002-6cff8f7de
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.3.0-20220315.0601-eecf75781
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.3.0-20220318.0201-4cf4ed59c
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.3.0-20220318.1607-d6d1da13a

# CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211029.0822-d63ba3a42
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211022.0601-4c62759e2  <-- worked
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211017.0002-ec2d009bf   <-- worked
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211014.0401-744608902
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211011.1801-7097d5a87 <-- worked
#SUBSCRIPTION_CHANNEL: 3.2-dev

#CATALOG_IMAGE: icr.io/cpopen/aiops-orchestrator-catalog:3.2-latest


