apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lvm-installation
  namespace: rook-ceph
  labels:
    app: lvm-installation
spec:
  selector:
    matchLabels:
      app: lvm-installation
  template:
    metadata:
      labels:
        app: lvm-installation
    spec:
      hostNetwork: true
      hostPID: true
      initContainers:
      - name: iscsi-installation
        command:
          - nsenter
          - --mount=/proc/1/ns/mnt
          - --
          - bash
          - -c
          - sudo yum install -y lvm2
        image: alpine:3.12
        securityContext:
          privileged: true
      containers:
      - name: sleep
        image: k8s.gcr.io/pause:3.1
  updateStrategy:
    type: RollingUpdate
