
apiVersion: batch/v1
kind: Job
metadata:
  name: aiops-install-aimanager-demo
  namespace: default
spec:
  serviceAccountName: installer-default-default
  template:
    spec:
      containers:
        - name: install
          image: niklaushirt/cp4waiops-tools:1.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "1256Mi"
              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              #set -x


              echo "*****************************************************************************************************************************"
              echo " ✅ STARTING: INSTALL ALL Components"
              echo "*****************************************************************************************************************************"
              echo ""
              echo ""
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 📥 Clone Repo $INSTALL_REPO"
              git clone $INSTALL_REPO
              cd cp4waiops-deployer
              echo ""
              echo ""



              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Prepare Ansible"
              ansible-galaxy collection install community.kubernetes:1.2.1
              ansible-galaxy collection install kubernetes.core:2.2.3
              ansible-galaxy collection install cloud.common
              pip install openshift pyyaml kubernetes 
              echo ""
              echo ""



              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Starting Installation"
              ansible-playbook ./ansible/00_aimanager-install-all.yaml -e ENTITLED_REGISTRY_KEY=$ENTITLED_REGISTRY_KEY
              echo ""
              echo ""
              echo "*****************************************************************************************************************************"
              echo " ✅ DONE"
              echo "*****************************************************************************************************************************"



              sleep 60000

          env:
          - name: INSTALL_REPO
            value : "https://github.com/niklaushirt/cp4waiops-public"
            # The pull token for cp.icr.com from https://myibm.ibm.com/products-services/containerlibrary
          - name: ENTITLED_REGISTRY_KEY
            value : "your_IBM_PULL_TOKEN"
      restartPolicy: Never
  backoffLimit: 4
