
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install ADDONS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Install OpenLDAP
# --------------------------------------------------------------------------------------------------------------------------------------
# - name: ADDONS -             ❎ Remove old OpenLDAP
#   kubernetes.core.k8s:
#     state: absent
#     template: ./templates/ldap/install-ldap.j2
#   #when: INSTALL_LDAP == true

- name: LDAP -               🚀 Install OpenLDAP
  kubernetes.core.k8s:
    state: present
    template: ./templates/ldap/install-ldap.j2
  #when: INSTALL_LDAP == true



