
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install CP4WAIOPS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: AI Manager -         🚀 Install Custom Resource - INSTALL AI MANAGER
  kubernetes.core.k8s:
    state: present
    template: './templates/waiops/4_waiops-install-template.j2'