apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    release: evtmanager
  name: evtmanager-gateway-allow-iduc
  namespace: noi
spec:
  ingress:
  - from: []
    ports:
      - protocol: TCP
        port: 4101
  podSelector:
    matchLabels:
      release: evtmanager
      appClass: objserv
  policyTypes:
  - Ingress
---
kind: Service
apiVersion: v1
metadata:
  name: evtmanager-objserv-agg-primary
  namespace: cp4waiops
spec:
  type: ExternalName
  externalName: evtmanager-objserv-agg-primary.noi.svc.cluster.local
  ports:
  - port: 4100
    name: primary-tds-port
  - port: 4101
    name: primary-iduc-port
---
kind: Service
apiVersion: v1
metadata:
  name: evtmanager-objserv-agg-backup
  namespace: cp4waiops
spec:
  type: ExternalName
  externalName: evtmanager-objserv-agg-backup.noi.svc.cluster.local
  ports:
  - port: 4100
    name: backup-tds-port
  - port: 4101
    name: backup-iduc-port
  - port: 4300
    name: agg-gate-tds-port
---
apiVersion: ai-manager.watson-aiops.ibm.com/v1beta1
kind: EventManagerGateway
metadata:
  name: eventmanagergateway
  namespace: cp4waiops
spec:
  logLevel: WARN
  license: accept
  objectServerPrimaryPort: 6001
  serviceAccountName: noi-service-account
  overrideProps: ''
  objectServerCAConfigmapName: ''
  objectServerBackupPort: 6002
  kafka:
    clusterName: iaf-system
    namespace: cp4waiops
    topicName: cp4waiops-cartridge-alerts-noi-lwt6jy65
    userName: cp4waiops-cartridge-kafka-auth
  objectServerPrimaryIP: ''
  objectServerPrimaryHost: aiops-proxy.cp4waiops.svc
  objectServerBackupIP: ''
  objectServerBackupHost: aiops-proxy.cp4waiops.svc
  replicationTypes:
    - INSERTS
    - UPDATES
  virtualPairName: AGG_V
  imagePullSecret: ibm-entitlement-key
  objectServerPrimaryIducHost: eventmanager-objserv-agg-primary
  omniSecretName: aiops-omni-secret
  objectServerBackupIducHost: eventmanager-objserv-agg-backup
  enableTransportDebugLog: false
  filter: Severity>=0
