apiVersion: ai-manager.watson-aiops.ibm.com/v1beta1
kind: EventManagerGateway
metadata:
  name: emg-noi
  namespace: aiops
spec:
  logLevel: DEBUG
  license: accept
  objectServerPrimaryPort: 6001
  serviceAccountName: ''
  overrideProps: ''
  objectServerCAConfigmapName: emg-omni-ca
  objectServerBackupPort: 6002
  kafka:
    clusterName: iaf-system
    namespace: ''
    topicName: cp4waiops-cartridge-alerts-noi-lwt6jy65
    userName: cp4waiops-cartridge-kafka-auth
  objectServerPrimaryIP: 
  objectServerPrimaryHost: aiops-proxy.noi.svc
  objectServerBackupIP: 
  objectServerBackupHost: aiops-proxy.noi.svc
  replicationTypes:
    - INSERTS
    - UPDATES
  virtualPairName: AGG_V
  imagePullSecret: ibm-entitlement-key
  objectServerPrimaryIducHost: aiops-objserv-agg-primary
  omniSecretName: evtmanager-omni-secret
  objectServerBackupIducHost: aiops-objserv-agg-backup
  enableTransportDebugLog: false
  filter: Severity=5


