apiVersion: ai-manager.watson-aiops.ibm.com/v1beta1
kind: EventManagerGateway
metadata:
  name: eventmanagergateway
  namespace: noi
spec:
  logLevel: WARN
  license:
    accept: true
  objectServerPrimaryPort: 6001
  serviceAccountName: noi-service-account
  overrideProps: ''
  objectServerCAConfigmapName: ''
  objectServerBackupPort: 6002
  kafka:
    clusterName: iaf-system
    namespace: cp4waiops
    topicName: cp4waiops-cartridge-alerts-noi-xuem3daq
    userName: cp4waiops-cartridge-kafka-auth
  objectServerPrimaryIP: ''
  objectServerPrimaryHost: evtmanager-proxy.noi.svc
  objectServerBackupIP: ''
  objectServerBackupHost: evtmanager-proxy.noi.svc
  replicationTypes:
    - INSERTS
  virtualPairName: AGG_V
  imagePullSecret: ibm-entitlement-key
  objectServerPrimaryIducHost: eventmanager-objserv-agg-primary
  omniSecretName: aiops-omni-secret
  objectServerBackupIducHost: eventmanager-objserv-agg-backup
  enableTransportDebugLog: false
  filter: Severity>=0
