

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for Zen in Common Services being ready
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************



- name: LOGGING -                📥 WRITE TO LOGFILE
  shell: |
    export MESSAGE=" 🚀 Starting Ai Manager Finalize Install (03_AIManager-finalize)"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "**********************************************************************************************************************************************************" >> ../installAIManager.log
    echo "**********************************************************************************************************************************************************" >> ../installAIManager.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes


