apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetoy-deployment
  namespace: kubetoy
  labels:
    app: kubetoy-app
spec:
    selector:
      matchLabels:
        app: kubetoy
    replicas: 1
    template:
      metadata:
        labels:
          app: kubetoy
      spec:
        containers:
        - name: kubetoy
          image: niklaushirt/kubetoy:0.3
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
          volumeMounts:
          - name: configvol
            mountPath: /var/config
          - name: secretvol
            mountPath: /var/secret
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
          - name: ENV_TOY_CONFIGMAP
            valueFrom: 
              configMapKeyRef:
                name: kubetoy-configmap-env
                key: ENV_TOY_CONFIGMAP
          - name: ENV_TOY_SECRET
            valueFrom:
              secretKeyRef:
                name: kubetoy-secret-env
                key: ENV_TOY_SECRET
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        volumes:
        - name: configvol
          configMap:
            name: kubetoy-configmap-files
        - name: secretvol
          secret:
            secretName: kubetoy-secret-files
---
apiVersion: v1
kind: Service
metadata:
  name: kubetoy-service
  namespace: kubetoy
  labels:
    app: kubetoy-app
spec:
  type: ClusterIP
  ports:
    - targetPort: 3000
      port: 3000
      protocol: TCP
      name: "http"
  selector:
    app: kubetoy
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubetoy-configmap-env
  namespace: kubetoy
data:
  ENV_TOY_CONFIGMAP: 'This is a configuration value.'
---
apiVersion: v1
kind: Secret
metadata:
  name: kubetoy-secret-env
  namespace: kubetoy
type: Opaque
data:
  ENV_TOY_SECRET: VGhpcyBpcyBhIHRlc3Q=
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubetoy-configmap-files
  namespace: kubetoy
data:
  config.json: '{ "default": "123" }'
---
apiVersion: v1
kind: Secret
metadata:
  name: kubetoy-secret-files
  namespace: kubetoy
type: Opaque
data:
  toy-secret.txt: U2hoLi4uIFRoaXMgaXMgYSBzZWNyZXQu
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kubetoy
  namespace: kubetoy
  labels:
    app: kubetoy-app
spec:
  subdomain: ''
  to:
    kind: Service
    name: kubetoy-service
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
