

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Open Doc
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


- name: INFRA MANAGER -              🌏 Get INFRA MANAGER LOGINS
  shell: |
    export INFRA_NAMESPACE=$(oc get po -A|grep ibm-infra-management-install-operator |awk '{print$1}')
    export INFRA_ROUTE=$(oc get route -n $INFRA_NAMESPACE cpd -o jsonpath={.spec.host})
    echo "                🌏 URL:      https://$INFRA_ROUTE"
    echo ""
    echo "                🧑 User:     $(oc -n ibm-common-services get secret platform-auth-idp-credentials -o jsonpath='{.data.admin_username}' | base64 --decode && echo)"
    echo "                🔐 Password: $(oc -n ibm-common-services get secret platform-auth-idp-credentials -o jsonpath='{.data.admin_password}' | base64 --decode)"

    export URL=https://$INFRA_ROUTE/
    if [ -x "$(command -v open)" ]; then
      open $URL
    else 
      if [ -x "$(command -v firefox)" ]; then
        firefox $URL
      else 
        if [ -x "$(command -v google-chrome)" ]; then
          google-chrome $URL
        fi
      fi
    fi
  ignore_errors: yes
  register: LOGINS


- name: INFRA MANAGER -              🟢 AI MANAGER LOGINS
  debug: 
    var: LOGINS.stdout_lines
