
stages:
  - build
  - promote

variables:
  BUILD_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:build-${CI_PIPELINE_ID}
  LATEST_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  DOCKER_IO_IMAGE: "docker.io/ibmicpcoc/kubetoy:latest"

build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$BUILD_IMAGE" .
    - docker push "$BUILD_IMAGE"

promote_prod:  
  stage: promote
  image: docker:18-git
  services:
    - docker:dind
  when: manual
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$BUILD_IMAGE"
    - docker tag "$BUILD_IMAGE" "$LATEST_IMAGE"
    - docker push "$LATEST_IMAGE"


