

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Open Doc
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


- name: DOCUMENTATION -          🌏 Open Documentation
  shell: |
    open https://github.ibm.com/NIKH/aiops-install-ansible-fvt-33#2-ai-manager-installation



