
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install ADDONS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Create OCP Demouser Account
# --------------------------------------------------------------------------------------------------------------------------------------

- name: TIMESTAMP -              🟢 START - CREATE USER
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: DEMO USER -              📥 WRITE TO LOGFILE
  shell: |
    export MESSAGE="Creating OCP User"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes



- name: DEMO USER -              🔎 Check OCP Demouser Account
  shell: |
    oc get serviceaccount --ignore-not-found -n default demo-admin
  ignore_errors: yes
  register: USER_EXISTS


- name: DEMO USER -              🩹 Create OCP Demouser Account
  shell: |
        oc project {{ WAIOPS_NAMESPACE }} 
        oc create serviceaccount -n default demo-admin
        oc create clusterrolebinding test-admin --clusterrole=cluster-admin --serviceaccount=default:demo-admin
        oc create clusterrolebinding ibm-zen-operator-serviceaccount --clusterrole=cluster-admin --serviceaccount=ibm-common-services:ibm-zen-operator-serviceaccount
  ignore_errors: yes
  register: demo_account
  when: USER_EXISTS.stdout|length == 0

