---

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Generic Event Webhook 
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: DEMO-UI -      👓 Load parameters
  include_vars: ../00_config_cp4waiops.yaml




- name: TOOLBOX -      🚀 DEPLOY TOOLBOX POD
  kubernetes.core.k8s:
    state: present
    template: ./templates/waiops-toolbox/create-waiops-toolbox.yaml
