apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-noi-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-noi-catalog
  publisher: IBM Content
  sourceType: grpc
  image: icr.io/cpopen/noi-operator-catalog:1.6.3.2-20211006212844
  updateStrategy:
    registryPoll:
      interval: 45m
