- name: TRAINING LOAD LAD -        🚀🚀 CREATE CLUSTERROLE
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: ./templates/training/default-cluserrole.yaml
    

- name: TRAINING LOAD LAD -        🚀 LOAD ELASTICSEARCH LOG DATA 
  kubernetes.core.k8s:
    state: present
    namespace: turbonomic
    src: ./templates/training/load-job-logs.yaml

- name: TRAINING LOAD LAD -        🕦 WAIT FOR COMPLETION
  shell: |
    while : ; do
          READY=$(oc get jobs -n default load-log-indexes)
          if [[ ! $READY  =~ "1/1" ]]; then
                echo "        Load Job not completed. Waiting 30 seconds"
                sleep 30
          else
                break
          fi
    done
    echo "      ✅ OK"
  register: ES_READY
  args:
    executable: /bin/bash


- name: TRAINING LOAD LAD -        🧻 CLEANUP JOB
  kubernetes.core.k8s:
    state: absent
    namespace: turbonomic
    src: ./templates/training/load-job-logs.yaml
  

- name: TRAINING LOAD LAD -        🧻 CLEANUP COMPLETED JOBS
  shell: |
    oc delete pod  -n default --ignore-not-found $(oc get po -n default|grep load-logs-indexes|awk '{print$1}')
  register: ES_READY
  ignore_errors: yes
