---
# tasks file for aiops
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Ansible Install Playbook V0.1
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# TEST SOME STUFF
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: LOAD PARAMETERS -        👓 Load parameters
  include_vars: ../00_config_cp4waiops.yaml

- name: TIMESTAMP -              🟢 START - INIT CHECKS
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: INIT CHECKS -            🟢 OCP_LOGIN
  debug: 
    var: OCP_LOGIN



- name: INIT CHECKS -            🟢 OCP_URL
  debug: 
    var: OCP_URL


- name: INIT CHECKS -            🟢 OCP_TOKEN
  debug: 
    var: OCP_TOKEN


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Login
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: INIT CHECKS -            🔐 Check Login credentials
  fail: msg="If you select auto-login, you have to provide Cluster credentials"
  when: OCP_LOGIN == true and OCP_URL=="not_configured" and OCP_TOKEN=="not_configured"


- name: INIT CHECKS -            👨‍💼 Login to cluster
  shell: "oc login --token={{ OCP_TOKEN }} --server={{ OCP_URL }}"   
  register: k8s_auth_results
  when: OCP_LOGIN == true



# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Checks
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: INIT CHECKS -            🔐 Check Entitlement provided
  fail: msg="Please provide IBM Entitlement Pull Secret Key/Token (Get it from here https://myibm.ibm.com/products-services/containerlibrary)"
  when: "ENTITLED_REGISTRY_KEY is not defined"

