---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-snow-indexes
  namespace: default
spec:
  serviceAccountName: demo-admin
  template:
    spec:
      containers:
        - name: load
          image: niklaushirt/cp4waiops-tools:1.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "1256Mi"
              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              #set -x

              echo "*****************************************************************************************************************************"
              echo " ✅ STARTING: Load service now training files"
              echo "*****************************************************************************************************************************"

              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              echo "    📥 Downloading service now training files"
              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              export AWX_REPO=https://github.com/niklaushirt/awx-waiops-trainingdata.git
              git clone $AWX_REPO

              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              echo "    🚀 Starting Data Load"
              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              cd awx-waiops-trainingdata
              ./training/robotshop-load-snow-for-training.sh

              echo "*****************************************************************************************************************************"
              echo " ✅ DONE"
              echo "*****************************************************************************************************************************"

          env:
            - name: INDEX_OVERWRITE
              value : "false"
            - name: VERSION
              value : "3.3"
      restartPolicy: Never

  backoffLimit: 4
