---
# Source: humio-helm-charts/charts/humio-fluentbit/templates/fluent-bit-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: humio-fluentbit-fluentbit-read
  namespace: humio-logging
---
# Source: humio-helm-charts/charts/humio-fluentbit/templates/fluent-bit-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: humio-fluentbit-fluent-bit-config
  namespace: humio-logging
  labels:
    k8s-app: humio-fluentbit
data:
  fluent-bit-service.conf:  |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

  fluent-bit-input.conf:  |-
    [INPUT]
        Name             tail
        Path             /var/log/containers/*bookinfo_*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    256MB
        Skip_Long_Lines  On
    [INPUT]
        Name             tail
        Path             /var/log/containers/*robot-shop_*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    256MB
        Skip_Long_Lines  On
    [INPUT]
        Name             tail
        Path             /var/log/containers/*qotd*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    256MB
        Skip_Long_Lines  On

  fluent-bit-filter.conf:  |-
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

  fluent-bit-output.conf:  |-
    [OUTPUT]
        Name  es
        Match *
        Host ${FLUENT_ELASTICSEARCH_HOST}
        Port ${FLUENT_ELASTICSEARCH_PORT}
        tls ${FLUENT_ELASTICSEARCH_TLS}
        tls.verify ${FLUENT_ELASTICSEARCH_TLS_VERIFY}
        HTTP_User ${HUMIO_REPO_NAME}
        HTTP_Passwd ${HUMIO_INGEST_TOKEN}
        Logstash_Format On
        Retry_Limit False
        Type  flb_type
        Time_Key @timestamp
        Replace_Dots On
        Logstash_Prefix FluentBitHelmChart
        Buffer_Size 5MB

  parsers.conf:  |-
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
  
    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
  
    [PARSER]
        Name   apache_error
        Format regex
        Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$
  
    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
  
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
  
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
  
    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S

  fluent-bit.conf: |-
    @INCLUDE fluent-bit-service.conf
    @INCLUDE fluent-bit-input.conf
    @INCLUDE fluent-bit-filter.conf
    @INCLUDE fluent-bit-output.conf

    @INCLUDE custom.conf


  custom.conf: ""
---
# Source: humio-helm-charts/charts/humio-fluentbit/templates/fluent-bit-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humio-fluentbit-fluentbit-read
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs: ["get", "list", "watch"]
---
# Source: humio-helm-charts/charts/humio-fluentbit/templates/fluent-bit-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: humio-fluentbit-fluentbit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: humio-fluentbit-fluentbit-read
subjects:
- kind: ServiceAccount
  name: humio-fluentbit-fluentbit-read
  namespace: humio-logging
---
# Source: humio-helm-charts/charts/humio-fluentbit/templates/fluent-bit-ds.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: humio-fluentbit-fluentbit
  namespace: humio-logging
  labels:
    k8s-app: humio-fluentbit
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: humio-fluentbit
  template:
    metadata:
      labels:
        k8s-app: humio-fluentbit
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:
      - name: humio-fluentbit
        image: fluent/fluent-bit:1.6.10
        command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf", "-H"]
        securityContext:
          privileged: true
        livenessProbe:
          httpGet:
            path: /api/v1/metrics
            port: 2020
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "humiocluster.humio-logging"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSEARCH_TLS
          value: "Off"
        - name: FLUENT_ELASTICSEARCH_TLS_VERIFY
          value: "Off"
        - name: HUMIO_REPO_NAME
          value: "defaultRepoName"
        - name: HUMIO_INGEST_TOKEN
          valueFrom:
            secretKeyRef:
              name: aiops-humioingesttoken
              key: token
        - name: FLUENT_HEC_HOST
          value: "cloud.humio.com"
        - name: FLUENT_HEC_PORT
          value: "443"
        - name: FLUENT_HEC_TLS
          value: "Off"
        - name: FLUENT_HEC_TLS_VERIFY
          value: "Off"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc/
        resources:
          limits:
            cpu: 256m
            memory: 500Mi
          requests:
            cpu: 128m
            memory: 256Mi
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: humio-fluentbit-fluent-bit-config
      serviceAccountName: humio-fluentbit-fluentbit-read
---
# Source: humio-helm-charts/charts/humio-fluentbit/templates/fluent-bit-scc.yaml
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: humio-fluentbit-fluentbit
allowPrivilegedContainer: true
allowHostNetwork: true
allowHostDirVolumePlugin: true
priority:
allowedCapabilities: []
allowHostPorts: true
allowHostPID: true
allowHostIPC: true
readOnlyRootFilesystem: false
requiredDropCapabilities: []
defaultAddCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - hostPath
  - persistentVolumeClaim
  - projected
  - secret
users:
  - system:serviceaccount:humio-logging:humio-fluentbit-fluentbit-read
---
# Source: humio-helm-charts/charts/humio-fluentbit/templates/fluent-bit-token-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: fluentbit-custom-token
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data:
  token: "Y2hhbmdlbWU="
