#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS v3.3
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - AWX (Open Source Ansible Tower) with preloaded Playbooks
#  - Disables ASM Service match rule 
#  - Train Models
#    - Create Training Definitions (TG, LAD, CR, SI. Turn off RSA) 
#    - Create Training Data (LAD, SNOW) 
#    - Train Models (TG, LAD, CR, SI) 
#  - Topology
#    - Create K8s Observer
#    - Create ASM merge rules
#    - Load ASM merge Topology
#    - Create AI Manager Application
#  - Creates valid certificate for Ingress (Slack) 

#  
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 

- hosts: localhost
  #become: true
  vars_files: ../00_config_cp4waiops.yaml

  roles:  

# Start block
    - role: 98-log-start-02

# Placeholder for customization
    - role: 00_init-custom-hook


# Run Prerequisites
    - role: 03_init-initialization
  
    - role: 05_init-get-storage-class
      

# Wait for CP4WAIOPS being completely installed
    - role: 99_aimanager-wait-cp4waiops

# Create Training definitions, load data
    - role: 85_aimanager-training-check-exists
    - role: 86_aimanager-training-create-tg-configuration
      when: TRAINING_EXISTS==false
    - role: 86_aimanager-training-create-metric-configuration
      when: TRAINING_EXISTS==false
    - role: 86_aimanager-training-create-snow-configuration
      when: TRAINING_EXISTS==false
    - role: 86_aimanager-training-create-logs-configuration
      when: TRAINING_EXISTS==false
    - role: 87_aimanager-training-load-snow
      when: TRAINING_EXISTS==false
    - role: 87_aimanager-training-load-logs
      when: TRAINING_EXISTS==false
    - role: 87_aimanager-training-load-metric
      when: TRAINING_EXISTS==false

# Load Topology
    #- role: 81_aimanager-create-observers
    - role: 82_aimanager-load-topology-merge
    - role: 83_aimanager-create-topology
    - role: 84_aimanager-create-aiops-application


# Create Kafka Connections
    - role: 34_aimanager-create-kafka-connections


# Install Add-Ons while data is loading
      
    - role: 23_addons-awx      
    - role: 99_aimanager-wait-awx
    - role: 35_aimanager-create-awx-connection

    - role: 47_aimanager-load-awx-playbooks-for-demo

    - role: 31_aimanager-patch-ingress
      
    - role: 32_aimanager-disable-match-token-rule

# Train models
    - role: 87_aimanager-training-load-wait
      when: TRAINING_EXISTS==false
    - role: 88_aimanager-training-run-snow
      when: TRAINING_EXISTS==false
    - role: 88_aimanager-training-run-logs
      when: TRAINING_EXISTS==false
    - role: 88_aimanager-training-run-metric
      when: TRAINING_EXISTS==false
      

# Open Post installation docs
    - role: 99_open-aimanager-usermgt
    
# Open Post installation docs
    - role: 99_open-doc-post-02

# Get all login credentials
    - role: 90_core-get-all-logins
      when: PRINT_LOGINS



# End block
    - role: 98-log-end-02



