#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS v3.4.0
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - Train Models
#    - Create Training Definitions (TG, LAD, CR, SI. Turn off RSA) 
#    - Create Training Data (LAD, SNOW) 
#    - Train Models (TG, LAD, CR, SI) 
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 

- hosts: localhost
  #become: true
  vars_files: ../00_config_cp4waiops.yaml

  roles:  

# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
    - role: 00_init-custom-hook

# Initialize Logging
    - role: 01_init-logging
    
    - role: 02_init_checks
# Start block
    - role: 98-log-start-01

# Run Prerequisites
    - role: 03_init-initialization
  
    - role: 04_storage-rook-ceph
      when: (ROOK_CEPH_INSTALL_MODE=="enable" or ROOK_CEPH_INSTALL_MODE=="automatic") and  INSTALL_ROOK_CEPH=="true"

    - role: 05_init-get-storage-class
      
#     - role: 06_aimanager-prerequisites
      




    
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# WAIT FOR INSTALLATION READY
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Wait for Common Services being completely installed
    - role: 99_aimanager-wait-common-services
    - role: 99_aimanager-wait-for-zen
      


# Wait for CP4WAIOPS being completely installed
    - role: 99_aimanager-wait-cp4waiops





 
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# CREATE MODEL TRAINING
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Create Training definitions, load data
    - role: 85_aimanager-training-check-exists
    - role: 86_aimanager-training-create-tg-configuration
      when: TRAINING_EXISTS==false
    - role: 86_aimanager-training-create-metric-configuration
      when: TRAINING_EXISTS==false
    - role: 86_aimanager-training-create-snow-configuration
      when: TRAINING_EXISTS==false
    - role: 86_aimanager-training-create-logs-configuration
      when: TRAINING_EXISTS==false
    - role: 87_aimanager-training-load-snow
      when: TRAINING_EXISTS==false
    - role: 87_aimanager-training-load-logs
      when: TRAINING_EXISTS==false
    - role: 87_aimanager-training-load-metric
      when: TRAINING_EXISTS==false




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# RUN MODEL TRAINING
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Train models
    - role: 87_aimanager-training-load-wait
      when: TRAINING_EXISTS==false
    - role: 88_aimanager-training-run-snow
      when: TRAINING_EXISTS==false
    - role: 88_aimanager-training-run-logs
      when: TRAINING_EXISTS==false
    - role: 88_aimanager-training-run-metric
      when: TRAINING_EXISTS==false
      



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# CREATE CONNECTIONS FOR INCEPTION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Create Kafka Connections
    - role: 34_aimanager-create-kafka-connections



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# FINALIZE
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Open Demo UI
    - role: 99_open-demoui
    
# Open AI MANAGER
    - role: 99_open-aimanager
    - role: 99_open-slack-apps
    - role: 99_open-aimanager-runbook
    - role: 99_open-aimanager-policies
    - role: 99_open-aimanager-usermgt
    
# Open Post installation docs
    - role: 99_open-doc-post-01



# Get all login credentials
    - role: 90_core-get-all-logins
      when: PRINT_LOGINS

# End block
    - role: 98-log-end-01