#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS v3.3
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - IBM Operator
#  - AI Manager
#  - OpenLDAP & Register with AI Manager
#  - AWX (Open Source Ansible Tower) with preloaded Playbooks
#  - RobotShop Demo App
#  - Demo Service Account 
#  - External Routes (Flink, Topology, ...)
#  - Disables ASM Service match rule 
#  - Creates valid certificate for Ingress (Slack) 
#  - Train Models
#    - Create Training Definitions (TG, LAD, CR, SI. Turn off RSA) 
#    - Create Training Data (LAD, SNOW) 
#    - Train Models (TG, LAD, CR, SI) 
#  
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 

- hosts: localhost
  #become: true
  vars_files: ../00_config_cp4waiops.yaml

  roles:  

# Start block
    - role: 98-log-start-03

# Placeholder for customization
    - role: 00_init-custom-hook

# Run Prerequisites
    - role: 03_init-initialization
  



# Install Add-Ons while CP4WAIOPS is coming up
    - role: 48_aimanager-load-runbooks-for-demo


# Restart Anomaly Pods to make anomaly detection workk
    #- role: 89_aimanager-reset-anomaly-detection

# Wait for CP4WAIOPS being completely installed
    #- role: 99_aimanager-wait-cp4waiops

# Install Demo UI    
    - role: 18_aimanager-demo-ui

# Open Post installation docs
    - role: 99_open-aimanager-runbook
    
# Open Post installation docs
    - role: 99_open-doc-post-03

# Get all login credentials
    - role: 90_core-get-all-logins
      when: PRINT_LOGINS



# End block
    - role: 98-log-end-03




