#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS v3.3
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - IBM Operator
#  - AI Manager
#  - OpenLDAP & Register with AI Manager
#  - RobotShop Demo App
#  - Demo Service Account 
#  
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 

- hosts: localhost
  #become: true
  vars_files: ../00_config_cp4waiops.yaml

  roles:  
# Placeholder for customization
    - role: 00_init-custom-hook

# Initialize Logging
    - role: 01_init-logging
    
    - role: 02_init_checks
# Start block
    - role: 98-log-start-01

# Run Prerequisites
    - role: 03_init-initialization
  
    - role: 04_storage-rook-ceph
      when: (ROOK_CEPH_INSTALL_MODE=="enable" or ROOK_CEPH_INSTALL_MODE=="automatic") and  INSTALL_ROOK_CEPH=="true"

    - role: 05_init-get-storage-class
      

    - role: 06_aimanager-prerequisites
      

# Install CP4WAIOPS Operator
    - role: 10_aimanager-custom-hook

    - role: 11_aimanager-operator
      
      
# Install CP4WAIOPS Instance
    - role: 12_aimanager-install
      



    

# Wait for Common Services being completely installed
    - role: 99_aimanager-wait-common-services
      

    - role: 99_aimanager-wait-for-zen
      




# Wait for CP4WAIOPS being completely installed
    - role: 99_aimanager-wait-cp4waiops
      


# Get all login credentials
    - role: 90_core-get-all-logins
      when: PRINT_LOGINS

# End block
    - role: 98-log-end-01