#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS 3.2
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


- hosts: localhost
  #become: true
  vars_files: ../00_config_cp4waiops.yaml

  roles:  
# Placeholder for customization
    - role: 00_pre

# Run Prerequisites
    - role: 01_initialization
      
  
    - role: 02_rook-ceph
      when: ROOK_CEPH_INSTALL_MODE=="enable" or ROOK_CEPH_INSTALL_MODE=="automatic"

    - role: 03_aiops-get-storage-class
      

    - role: 04_aiops-prerequisites
      

# Install CP4WAIOPS Operator
    - role: 10_aiops-operator
      
      
# Install CP4WAIOPS Instance
    - role: 11_aiops-install
      


# Install Add-Ons while CP4WAIOPS is coming up
    - role: 25_aiops-addons-ldap

    - role: 26_aiops-addons-user

    - role: 27_aiops-addons-demoapps

    - role: 28_aiops-addons-runbook-bastion
      



# Wait for Common Services being completely installed
    - role: 99_aiops-wait-common-services
      

    - role: 99_aiops-wait-for-zen
      

    - role: 30_aiops-patches


# Wait for CP4WAIOPS being completely installed
    - role: 99_aiops-wait-cp4waiops
      

    - role: 31_aiops-final-patches
      

# Post installation tasks
    - role: 40_aiops-post-ldap-register






# Get all login credentials
    - role: 90_aiops-logins
      when: PRINT_LOGINS











