#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS v3.3
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - ASM Merge Topology
#  - ASM Topology Merge rules
#  - AI Manager Application
#  - AI Manager Runbook
#  
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


- hosts: localhost
  #become: true
  vars_files: ../00_config_cp4waiops.yaml

  roles:  
# Placeholder for customization
    - role: 00_pre

# Before launching this you have to do the following (https://github.ibm.com/NIKH/aiops-install-ansible-fvt-33#41-add-ldap-logins-to-cp4waiops-%F0%9F%85%B0%EF%B8%8F):
#
#   Basic Configuration
#     Configure LDAP Logins
#
#   Configure Topology 
#     Create REST Observer
#     Create Topology (🐥 - Option 51)
#
#   Models Training
#     Train the Models (🐥 - Option 55)
#     Create Integrations
#
#   Advanced Configuration
#     Enable Story creation Policy
#     Create AWX Connection
#     Create AI Manager Runbook

    - role: 80_load-topology-all.yaml

    - role: 48_aiops-load-aimanager-runbooks.yaml

    #- role: 49_aiops-load-awx-aiops-playbooks.yaml


# And after the script has run (https://github.ibm.com/NIKH/aiops-install-ansible-fvt-33#47-create-runbook-policy-%F0%9F%85%B0%EF%B8%8F):
#     Create Runbook Policy



# Get all login credentials
    - role: 90_aiops-logins
      when: PRINT_LOGINS











