#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing Turbonomic for CP4WAIOPS v3.3
#
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  -  Patch Ingress policy-group
#  -  Create Topology Route - topology-merge
#  -  Create Topology Route - topology-rest
#  -  Create Topology Route - topology-file
#  -  Create Topology Route - topology-manage
#  -  Create external Flink Job Manager Route (you can ignore errors in this step)
#  -  Create external AI Manager API Route (you can ignore errors in this step)
#  -  Create external Datalayer API Route (you can ignore errors in this step)
#  -  Delete Pods with ImgPull Error  (you can ignore errors in this step)
#  
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

- hosts: localhost
  #become: true
  vars_files: ../00_config_cp4waiops.yaml

  roles:
    - role: 30_aimanager-create-routes
    














