#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing Turbonomic for CP4WAIOPS v3.3
#
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - Create definition Temporal Grouping 
#  - Create definition Similar Incidents
#  - Create definition Change Risk
#  - Create definition Log Anomaly Detection
#  - Load SNOW data into ElasticSearch for training
#  - Load LOG data into ElasticSearch for training
#  - Wait for load to finish
#  - Run training Similar Incidents
#  - Run training Change Risk
#  - Run training Log Anomaly Detection
#  
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

- hosts: localhost
  #become: true
  vars_files: ../00_config_cp4waiops.yaml

  roles: 
# Placeholder for customization
    - role: 00_init-custom-hook


# Run Roles 

    - role: 85_aimanager-training-check-exists
    - role: 86_aimanager-training-create-tg-configuration
      when: TRAINING_EXISTS==false
    - role: 86_aimanager-training-create-metric-configuration
      when: TRAINING_EXISTS==false
    - role: 86_aimanager-training-create-snow-configuration
      when: TRAINING_EXISTS==false
    - role: 86_aimanager-training-create-logs-configuration
      when: TRAINING_EXISTS==false
    - role: 87_aimanager-training-load-snow
      when: TRAINING_EXISTS==false
    - role: 87_aimanager-training-load-logs
      when: TRAINING_EXISTS==false
    - role: 87_aimanager-training-load-metric
      when: TRAINING_EXISTS==false

    - role: 87_aimanager-training-load-wait
      when: TRAINING_EXISTS==false
    - role: 88_aimanager-training-run-snow
      when: TRAINING_EXISTS==false
    - role: 88_aimanager-training-run-logs
      when: TRAINING_EXISTS==false
    - role: 88_aimanager-training-run-metric
      when: TRAINING_EXISTS==false


















