
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Waiting for CP4WAIOPS installation to finish
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
    


# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for {{ WAIOPS_NAMESPACE }} Namespace to be ready
# --------------------------------------------------------------------------------------------------------------------------------------

- name: CHECK -          🕦 Wait for more than >{{ WAIOPS_NS_MIN_PODS_FINAL }} pods in namespace {{ WAIOPS_NAMESPACE }}
  shell: |
    NUM_PODS=$(oc get po -n {{ WAIOPS_NAMESPACE }} | wc -l)
    echo $NUM_PODS
  register: kubectl_num_pods
  until: kubectl_num_pods.stdout|int > WAIOPS_NS_MIN_PODS_FINAL
  retries: 500
  delay: 15




- name: CHECK -          🕦 Wait for {{ WAIOPS_NAMESPACE }} to become ready
  shell: oc get po -n {{ WAIOPS_NAMESPACE }} | grep -v Running |grep -v Completed|grep -v Error |grep -v zen-tour-job| wc -l| tr -d ' '
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|int == 1
  retries: 500
  delay: 15


- name: CHECK -          🕦 Wait for all Pods in {{ WAIOPS_NAMESPACE }} to become ready
  shell: oc get po -n {{ WAIOPS_NAMESPACE }} | grep -v Completed | grep -v Error |grep "0/" |wc -l| tr -d ' '
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout == "0"
  retries: 500
  delay: 15

