- name: TIMESTAMP -              🟢 START - RUN LOG TRAINING
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: TRAINING RUN -           📥 WRITE TO LOGFILE
  shell: |
    export MESSAGE="Run LAD Training"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../installAIManager.log
  ignore_errors: yes


- name: TRAINING RUN -           🚀 RUN TRAINING LAD
  shell: |
    set -x
    
    echo "  ***************************************************************************************************************************************************"
    echo "   🛠️  Run Analysis: Log Anomaly Detection"
    export FILE_NAME=run-analysis-LAD.graphql
    ../tools/02_training/scripts/execute-graphql.sh

  register: output_string
  ignore_errors: yes
- name: TRAINING RUN LAD -       ✅ RESULT
  debug: 
    var: output_string.stdout_lines
  #when: PRINT_LOGINS == true

