
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Patches
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# Patch Ingress
# --------------------------------------------------------------------------------------------------------------------------------------
- name: PATCH -             🩹 Patch Ingress
  shell: oc patch namespace default --type=json -p '[{"op":"add","path":"/metadata/labels","value":{"network.openshift.io/policy-group":"ingress"}}]'
  register: ingress_patched


# - name: CONFIG -             🩹 Patch AIOpsAnalyticsOrchestrator Pull Secret
#   shell: oc patch AIOpsAnalyticsOrchestrator aiops -n {{ WAIOPS_NAMESPACE }} --type merge  --patch-file ./templates/waiops/patches/analytics-pull-patch.yaml
#   ignore_errors: yes
#   register: irorchestrator_patched




# --------------------------------------------------------------------------------------------------------------------------------------
# Delete ImgPull error pods
# --------------------------------------------------------------------------------------------------------------------------------------
- name: PATCH -             🩹 Delete Pods with ImgPull Error (hack for v3.3)
  shell: |
        errorPods=$(oc get po -n {{ WAIOPS_NAMESPACE }}|grep ImagePull|awk '{print$1}')
        if [[ ! $errorPods == "" ]]; then
          echo "Refreshing Pods"
          oc delete pod --ignore-not-found $(oc get po -n {{ WAIOPS_NAMESPACE }}|grep ImagePull|awk '{print$1}') -n {{ WAIOPS_NAMESPACE }}>/dev/null 2>/dev/null
        fi
  ignore_errors: yes

  

# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for Topology Pods
# --------------------------------------------------------------------------------------------------------------------------------------
- name: PATCH -             🕦 Wait for Topology Pods to become available - this can take up to 45 minutes (hack for v3.3)
  shell: oc get po -n {{ WAIOPS_NAMESPACE }} | grep aiops-topology-merge| grep -c ""
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout == "1"
  retries: 500
  delay: 15


# --------------------------------------------------------------------------------------------------------------------------------------
# Patch Topology Pods
# --------------------------------------------------------------------------------------------------------------------------------------
- name: PATCH -             🩹 Patch aiops-topology-merge (hack for v3.3)
  shell: oc patch deployment aiops-topology-merge -n {{ WAIOPS_NAMESPACE }} --patch-file ./templates/waiops/patches/aiops-topology-merge-patch.yaml
  ignore_errors: yes


- name: PATCH -             🩹 Patch aiops-topology-search (hack for v3.3)
  shell: oc patch deployment aiops-topology-search -n {{ WAIOPS_NAMESPACE }} --patch-file ./templates/waiops/patches/aiops-topology-search-patch.yaml
  ignore_errors: yes


- name: PATCH -             🩹 Patch aiops-topology-status (hack for v3.3)
  shell: oc patch deployment aiops-topology-status -n {{ WAIOPS_NAMESPACE }} --patch-file ./templates/waiops/patches/aiops-topology-status-patch.yaml
  ignore_errors: yes


- name: PATCH -             🩹 Patch aiops-topology-layout (hack for v3.3)
  shell: oc patch deployment aiops-topology-layout -n {{ WAIOPS_NAMESPACE }} --patch-file ./templates/waiops/patches/aiops-topology-layout-patch.yaml
  ignore_errors: yes

