# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install Runbook Bastion Server
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
    

- name: BASTION -            🔎 Check Runbook Bastion Server
  shell: |
    oc get deployment --ignore-not-found bastion-host -n default
  ignore_errors: yes
  register: OBJECT_EXISTS

# --------------------------------------------------------------------------------------------------------------------------------------
# Install Runbook Bastion Server
# --------------------------------------------------------------------------------------------------------------------------------------
- name: BASTION -            🚀 Install Runbook Bastion Server
  kubernetes.core.k8s:
    state: present
    namespace: "default"
    template: ./templates/runbook_bastion/create-bastion.yaml
  when: OBJECT_EXISTS.stdout|length == 0
